SELECT 'id --> pid' AS FD, CASE WHEN COUNT(*) = 0 THEN 'HOLDS' ELSE 'DOES NOT HOLD' END AS VALIDITY
FROM (
SELECT id, COUNT(DISTINCT pid)
FROM projects
GROUP BY id
HAVING COUNT(DISTINCT pid) > 1
) X;
SELECT 'pid --> pn' AS FD, CASE WHEN COUNT(*) = 0 THEN 'HOLDS' ELSE 'DOES NOT HOLD' END AS VALIDITY
FROM (
SELECT pid, COUNT(DISTINCT pn)
FROM projects
GROUP BY pid
HAVING COUNT(DISTINCT pn) > 1
) X;
SELECT 'did --> dn' AS FD, CASE WHEN COUNT(*) = 0 THEN 'HOLDS' ELSE 'DOES NOT HOLD' END AS VALIDITY
FROM (
SELECT did, COUNT(DISTINCT dn)
FROM projects
GROUP BY did
HAVING COUNT(DISTINCT dn) > 1
) X;
SELECT 'did --> dm' AS FD, CASE WHEN COUNT(*) = 0 THEN 'HOLDS' ELSE 'DOES NOT HOLD' END AS VALIDITY
FROM (
SELECT did, COUNT(DISTINCT dm)
FROM projects
GROUP BY did
HAVING COUNT(DISTINCT dm) > 1
) X;
